= Kakoune MindMap

== Overview

To use this plugin, export an environment variable available in your
shell, named `KAK_MINDMAP_DIR`, and set it to some directory you like
(e.g. ~/Documents/Notes) (and make sure it exists). Notes will be created
and searched for there.

By default, the `mindmap_new_note_fmt` option is set to `md` for Markdown;
but you can change this to `adoc`/`asciidoc` for AsciiDoc instead.

Really the only difference in behavior with these different file formats is
how this plugin will try to find a title for the note: in Markdown it will
use the value of the `title` field within the frontmatter; in AsciiDoc it's
the first line found to begin with the equals sign.

For any `.md` or `.adoc`/`.asciidoc` file you open, a hook checks to see if
another file named `.kakmindmap` happens to be exist in any of the current
file's parent directories.

If you want other "MindMaps" outside of `KAK_MINDMAP_DIR`, you can have them
sourced without manually updating the environment variable or the Kakoune
option. Just create the `.kakmindmap` file at the top-level of any other
notes source locations.

By default, notes created with the `mindmap-new-note` command will be created
under a directory structure that represents the date at which it was created:
`YYYY/MMM/DD/`. The default note filename will be an ID in the form of UNIX
time: `SSSSSSSSSS.(md/adoc/asciidoc)`. All notes should at least follow this
filename convention for the plugin to be usable.

This documentation also ignores commands and options which are largely
irrelevant for simply using this plugin. You can check the docstrings in the
source for the logic.

== Commands

=== mindmap-list

Creates a new buffer named `\*mindmap-list\*` which contains the list of
your notes with their titles. It also provides a shortcut to quickly open
the note where your cursor's at, if you hit <ret>.

=== mindmap-new-note

Automatically creates for you a new note following the schema that originates
from <<mindmap_dir_schema_cmd,mindmap_dir_schema_cmd>>.

== Options

=== mindmap_dir_schema_cmd

This is a command that should provide a valid directory schema for notes to be
created in. I.e. having slashes and valid directory names.

=== mindmap_new_note_fmt

Your preferred file format to be used when creating new notes. Basically just
the file extension use in the generated filename.
