= Kakoune MindMap

To use this... TODO

== Options

These options are accessible from this thing -> %opt{}. (Insert the option name in the brackets)

=== mindmap_dir

This should be set to a directory that contains a file named ".kakmindmap". Commands will use it as the location for managing notes. A hook is set to automatically detect and set it for you on opening buffers with files ending in .adoc/.asciidoc. You can also define the environment variable KAK_MINDMAP_DIR in your shell to set a default location for managing notes.

=== mindmap_newnote_extension

Pretty self-explanatory. Default is ".adoc".

=== mindmap_newnote_namer

A shell command of which the output will be used as the file name (before having <<mindmap_newnote_extension,mindmap_newnote_extension>> appended). The default is "date +%s", which returns UNIX time.

== Commands

=== mindmap-dir-detect

Looks for the '.kakmindmap' file in the same directory as the current file you have open. Sets %opt{mindmap_dir} to the same directory if it is found.

mindmap-note-new

Quickly opens up a new buffer for a new note. If you want, specify a custom file name (without the extension).

mindmap-nav-next

mindmap-nav-previous
